version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: 
          name: first
          command: npm run lint
          #when: on_fail
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: 
          name: first
          command: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: 
          name: first
          command: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  
      - analyze:
         requires:
            - test
